### ISSUE TITLE
Общее количество часов по дисциплине должно включать часы проведения экзамена

### ISSUE THREAD

**Issue by wowace** [voffan/umo#5]

**Comment by wowace** [comment]
В модели DisciplineDetails:
![image](https://user-images.githubusercontent.com/3712774/50547936-6b30f680-0c87-11e9-91ab-057da4761a01.png)

**Comment by voffan** [comment]
Если тип контроля экзамен, то добавить 36 часов, т.к. на экзамен выделяется 1 зет.
